version: "3.8"
services:
  db:
    image: postgres
    restart: always
    hostname: 127.0.0.1
    env_file: ./.env
    volumes:
      - ./:/usr/src/app
    ports:
      - 5432:5432
  redis:
    image: redis:4.0-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
      driver: none
  web:
    build:
      context: .
      dockerfile: ./docker/DockerFile
    command: bundle exec rails s -p 3000 -e development -b '0.0.0.0'
    env_file:
      - ./.env
    entrypoint: ["./docker/entrypoint.sh"]
    environment:
      RAILS_ENV: "${RAILS_ENV}"
    volumes:
      - ../:/rails-app
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
volumes:
  db:
  bundle:
  redis: