FROM ruby:3.2.2-bullseye

RUN apt-get clean all && apt-get update -qq && apt-get install -y build-essential libpq-dev \
    curl gnupg2 apt-utils  postgresql-client postgresql-server-dev-all git libcurl3-dev cmake \
    libssl-dev pkg-config openssl imagemagick file nodejs npm yarn


RUN mkdir /api
WORKDIR /api

COPY ../Gemfile Gemfile
COPY ../Gemfile.lock Gemfile.lock
RUN gem install bundler -v 2.4.14
RUN gem install rails
RUN bundle install

COPY . .

RUN chmod +x ./docker/entrypoint.sh
ENTRYPOINT ["./docker/entrypoint.sh"]

CMD ["server"]