default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['POSTGRES_DB'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  database: <%= ENV['POSTGRES_DB'] || 'db_dev' %>
  username: <%= ENV['POSTGRES_USER'] || 'root' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'root' %>


test:
  <<: *default
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  database: <%= ENV['POSTGRES_DB_TEST'] || 'test' %>
  username: <%= ENV['POSTGRES_USER'] || 'root' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'root' %>

production:
  <<: *default
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  database: <%= ENV['POSTGRES_DB_PRODUCTION'] || 'production' %>
  username: <%= ENV['POSTGRES_USER'] || 'root' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'root' %>